import { readTranscriptWorkbook } from "./workbook";
import type { CategoryKey, ParseResult, TranscriptCourse } from "../../shared/types/graduation";
import type { TranscriptAdapter } from "./types";
type RawRow = Record<string, unknown>;
const CATEGORY_BY_LABEL: Record<string, CategoryKey> = { 교양필수: "generalRequired", 교필: "generalRequired", 교양선택: "generalElective", 교선: "generalElective", 전공기초: "majorFoundation", 전기: "majorFoundation", 전공필수: "majorRequired", 전필: "majorRequired", 전공선택: "majorElective", 전선: "majorElective", 일반선택: "freeElective", 일선: "freeElective", 일반: "freeElective" };
const text = (value: unknown) => String(value ?? "").trim(); const number = (value: unknown) => { const parsed = Number.parseFloat(text(value).replace(/,/g, "")); return Number.isFinite(parsed) ? parsed : 0; };
function value(row: RawRow, ...keys: string[]) { for (const key of keys) if (Object.prototype.hasOwnProperty.call(row, key)) return row[key]; return ""; }
function isPassed(grade: string, semester: string, credits: number) {
  if (!Number.isFinite(credits) || credits < 0) return false;
  const normalized = grade.replace(/\s/g, "").toUpperCase();
  if (["F", "NP", "U", "W", "미이수", "수강취소", "포기", "FAIL", "N"].includes(normalized)) return false;
  if (semester.includes("편입생 인정학점") && !normalized) return true;
  return /^[ABCD][+0-]?$/.test(normalized) || ["P", "PASS", "S", "이수", "이수필"].includes(normalized);
}
export const kmouTranscriptAdapter: TranscriptAdapter = { id: "kmou-tis-v1", universityId: "kmou", normalizeRows(rows, rule) { return rows.map((row, index) => { const code = text(value(row, "교과목번호", "과목번호", "courseCode")); const name = text(value(row, "교과목명", "과목명", "courseName")); const rawCategory = text(value(row, "교과목구분▼", "교과목구분", "이수구분", "category")); const semester = text(value(row, "학기", "semester")); const credits = number(value(row, "학점", "credits")); const grade = text(value(row, "등급", "성적", "grade")); const mapped = CATEGORY_BY_LABEL[rawCategory.replace(/\s/g, "")]; const category = mapped ?? "freeElective"; const categoryRecognition = mapped ? "recognized" as const : "unrecognized" as const; return { rowNumber: number(value(row, "No", "번호")) || index + 1, year: text(value(row, "년도", "연도", "year")), semester, code, name, rawCategory, category, categoryRecognition, credits, grade, professor: text(value(row, "담당교수", "교수명", "professor")), englishName: text(value(row, "교과목명(영문)", "영문교과목명", "englishName")), passed: isPassed(grade, semester, credits), transferCredit: semester.includes("편입생 인정학점"), reclassified: false } satisfies TranscriptCourse; }).filter((course) => course.code || course.name); }, parse(buffer, rule): ParseResult { const { rows, sheetName, headers } = readTranscriptWorkbook(buffer); const courses = this.normalizeRows(rows, rule); const excludedRows = courses.filter((course) => !course.passed).length; const unclassified = courses.filter((course) => course.passed && course.categoryRecognition === "unrecognized"); const warnings: string[] = []; if (!headers.includes("교과목구분▼") && !headers.includes("교과목구분")) warnings.push("교과목 구분 열을 찾지 못해 영역별 판정을 보류했습니다."); if (unclassified.length) warnings.push(`알 수 없는 이수구분 ${unclassified.length}개 행은 일반선택으로 임의 합산하지 않고 확인 필요로 표시했습니다.`); if (courses.some((course) => !course.code)) warnings.push("과목번호가 없는 행은 과목명으로만 표시했습니다."); if (excludedRows) warnings.push(`등급이 없거나 미이수인 ${excludedRows}개 행은 취득학점에서 제외했습니다.`); return { sheetName, courses, warnings, recognizedRows: courses.length, excludedRows }; } };
