import { extractRuleWithOpenAI } from "./openai-ingestion"; import { createSourceDocument, saveCandidate } from "./rule-repository"; import { validateRuleSet } from "../rule-validator"; import type { DocumentTargetKey, GraduationRuleSet, IngestionDocument, RuleKey } from "../types";
const MAX_BYTES = 15 * 1024 * 1024; const ALLOWED_HOSTS = new Set(["kmou.ac.kr", "www.kmou.ac.kr"]); const ALLOWED_EXTENSIONS = /\.(pdf|xlsx|xls|docx|json)$/i;
function assertOfficialUrl(value: string) { const url = new URL(value); if (url.protocol !== "https:" || !ALLOWED_HOSTS.has(url.hostname.toLowerCase())) throw new Error("한국해양대학교 공식 HTTPS 주소만 수집할 수 있습니다."); return url; }
const cleanFileName = (value: string) => (value.split(/[\\/]/).pop()?.replace(/[^0-9a-zA-Z가-힣._-]/g, "_") || "official-document").slice(0, 160);
async function sha256(bytes: ArrayBuffer) { return [...new Uint8Array(await crypto.subtle.digest("SHA-256", bytes))].map((value) => value.toString(16).padStart(2, "0")).join(""); }
async function safeFetch(initial: URL): Promise<Response> { let current = initial; for (let attempt = 0; attempt < 4; attempt += 1) { const response = await fetch(current, { redirect: "manual", headers: { "User-Agent": "GradCompass/1.0" } }); if (![301, 302, 303, 307, 308].includes(response.status)) return response; const location = response.headers.get("location"); if (!location) return response; current = assertOfficialUrl(new URL(location, current).toString()); } throw new Error("공식 문서 리디렉션 횟수가 너무 많습니다."); }
async function resolveDownload(sourceUrl: string) { const pageUrl = assertOfficialUrl(sourceUrl); const pageResponse = await safeFetch(pageUrl); if (!(pageResponse.headers.get("content-type") ?? "").includes("text/html")) return { url: pageUrl, response: pageResponse }; const html = await pageResponse.text(); const hrefs = [...html.matchAll(/href=["']([^"']+)["']/gi)].map((match) => match[1]); for (const href of hrefs) { const candidate = new URL(href.replace(/&amp;/g, "&"), pageUrl); if (!ALLOWED_HOSTS.has(candidate.hostname.toLowerCase())) continue; if (!ALLOWED_EXTENSIONS.test(candidate.pathname) && !/download|atch|file/i.test(candidate.pathname + candidate.search)) continue; const response = await safeFetch(assertOfficialUrl(candidate.toString())); if (response.ok && !(response.headers.get("content-type") ?? "").includes("text/html")) return { url: candidate, response }; } throw new Error("공지에서 지원하는 첨부파일을 찾지 못했습니다."); }
async function ingestBytes(fileName: string, contentType: string, bytes: ArrayBuffer, sourceUrl: string | null, target: DocumentTargetKey): Promise<IngestionDocument> { if (bytes.byteLength > MAX_BYTES) throw new Error("공식 문서는 15MB 이하여야 합니다."); if (!ALLOWED_EXTENSIONS.test(fileName)) throw new Error("PDF, Excel, DOCX, JSON 공식 문서만 지원합니다."); const ruleKey: RuleKey = { universityId: target.universityId, admissionYear: target.admissionYear, departmentId: target.departmentId }; const document = await createSourceDocument({ fileName, sourceUrl, ...target, status: "extracting", sha256: await sha256(bytes), contentType, bytes }); if (["approved", "review_pending", "gpt_pending"].includes(document.status)) return document; try { let candidate: GraduationRuleSet | null = /json/i.test(contentType) || fileName.endsWith(".json") ? JSON.parse(new TextDecoder().decode(bytes)) as GraduationRuleSet : await extractRuleWithOpenAI(fileName, contentType, bytes, ruleKey); if (!candidate) { const errors = ["OPENAI_API_KEY 설정 후 GPT 구조화가 필요합니다."]; await saveCandidate(document.id, "gpt_pending", null, errors); return { ...document, status: "gpt_pending", validationErrors: errors }; } candidate = { ...candidate, schemaVersion: "1.0", status: "draft", key: ruleKey }; const errors = validateRuleSet(candidate); await saveCandidate(document.id, errors.length ? "failed" : "review_pending", candidate, errors); return { ...document, status: errors.length ? "failed" : "review_pending", candidateVersion: candidate.version, candidateRule: candidate, validationErrors: errors }; } catch (error) { const errors = [error instanceof Error ? error.message : "구조화 실패"]; await saveCandidate(document.id, "failed", null, errors); return { ...document, status: "failed", validationErrors: errors }; } }
export async function collectOfficialDocument(sourceUrl: string, target: DocumentTargetKey) { const { url, response } = await resolveDownload(sourceUrl); if (!response.ok) throw new Error(`공식 문서를 내려받지 못했습니다 (${response.status}).`); let fileName = cleanFileName(url.pathname.split("/").pop() || "official-document"); const type = response.headers.get("content-type") ?? "application/octet-stream"; if (!ALLOWED_EXTENSIONS.test(fileName)) fileName += type.includes("pdf") ? ".pdf" : type.includes("spreadsheet") || type.includes("excel") ? ".xlsx" : type.includes("json") ? ".json" : ""; return ingestBytes(fileName, type, await response.arrayBuffer(), sourceUrl, target); }
export async function uploadOfficialDocument(file: File, target: DocumentTargetKey) { return ingestBytes(cleanFileName(file.name), file.type || "application/octet-stream", await file.arrayBuffer(), null, target); }
