import * as XLSX from "xlsx";
import type { CategoryKey, ParseResult, TranscriptCourse } from "../types";
import type { TranscriptAdapter } from "./types";
type RawRow = Record<string, unknown>;
const CATEGORY_BY_LABEL: Record<string, CategoryKey> = { 교양필수: "generalRequired", 교필: "generalRequired", 교양선택: "generalElective", 교선: "generalElective", 전공기초: "majorFoundation", 전기: "majorFoundation", 전공필수: "majorRequired", 전필: "majorRequired", 전공선택: "majorElective", 전선: "majorElective", 일반선택: "freeElective", 일선: "freeElective", 일반: "freeElective" };
const text = (value: unknown) => String(value ?? "").trim(); const number = (value: unknown) => { const parsed = Number.parseFloat(text(value).replace(/,/g, "")); return Number.isFinite(parsed) ? parsed : 0; };
function value(row: RawRow, ...keys: string[]) { for (const key of keys) if (Object.prototype.hasOwnProperty.call(row, key)) return row[key]; return ""; }
function isPassed(grade: string, semester: string, credits: number) { if (credits < 0) return false; if (semester.includes("편입생 인정학점")) return true; const normalized = grade.replace(/\s/g, "").toUpperCase(); return Boolean(normalized) && !["F", "NP", "U", "W", "미이수", "수강취소", "포기", "FAIL", "N"].includes(normalized); }
export const kmouTranscriptAdapter: TranscriptAdapter = { id: "kmou-tis-v1", universityId: "kmou", normalizeRows(rows, rule) { const forced = new Map(rule.courseOverrides.map((item) => [item.courseCode.toUpperCase(), item.category])); return rows.map((row, index) => { const code = text(value(row, "교과목번호", "과목번호", "courseCode")); const name = text(value(row, "교과목명", "과목명", "courseName")); const rawCategory = text(value(row, "교과목구분▼", "교과목구분", "이수구분", "category")); const semester = text(value(row, "학기", "semester")); const credits = number(value(row, "학점", "credits")); const grade = text(value(row, "등급", "성적", "grade")); const mapped = CATEGORY_BY_LABEL[rawCategory.replace(/\s/g, "")]; const forcedCategory = forced.get(code.toUpperCase()); const original = mapped ?? "freeElective"; const category = forcedCategory ?? original; const categoryRecognition = forcedCategory || mapped ? "recognized" as const : "unrecognized" as const; return { rowNumber: number(value(row, "No", "번호")) || index + 1, year: text(value(row, "년도", "연도", "year")), semester, code, name, rawCategory, category, categoryRecognition, credits, grade, professor: text(value(row, "담당교수", "교수명", "professor")), englishName: text(value(row, "교과목명(영문)", "영문교과목명", "englishName")), passed: isPassed(grade, semester, credits), transferCredit: semester.includes("편입생 인정학점"), reclassified: Boolean(forcedCategory) && category !== original } satisfies TranscriptCourse; }).filter((course) => course.code || course.name); }, parse(buffer, rule): ParseResult { const workbook = XLSX.read(buffer, { type: "array", cellDates: false }); const sheetName = workbook.SheetNames[0]; if (!sheetName) throw new Error("엑셀 파일에서 시트를 찾지 못했습니다."); const rows = XLSX.utils.sheet_to_json<RawRow>(workbook.Sheets[sheetName], { defval: "", raw: false }); if (!rows.length) throw new Error("성적 데이터가 비어 있습니다."); const headers = Object.keys(rows[0]); const missing = ["교과목번호", "교과목명", "학점"].filter((header) => !headers.includes(header)); if (missing.length) throw new Error(`종합정보시스템 성적 파일 형식과 다릅니다: ${missing.join(", ")} 열이 필요합니다.`); const courses = this.normalizeRows(rows, rule); const excludedRows = courses.filter((course) => !course.passed).length; const unclassified = courses.filter((course) => course.passed && course.categoryRecognition === "unrecognized"); const warnings: string[] = []; if (!headers.includes("교과목구분▼") && !headers.includes("교과목구분")) warnings.push("교과목 구분 열을 찾지 못해 영역별 판정을 보류했습니다."); if (unclassified.length) warnings.push(`알 수 없는 이수구분 ${unclassified.length}개 행은 일반선택으로 임의 합산하지 않고 확인 필요로 표시했습니다.`); if (courses.some((course) => !course.code)) warnings.push("과목번호가 없는 행은 과목명으로만 표시했습니다."); if (excludedRows) warnings.push(`등급이 없거나 미이수인 ${excludedRows}개 행은 취득학점에서 제외했습니다.`); return { sheetName, courses, warnings, recognizedRows: courses.length, excludedRows }; } };
