import type { CourseGuidance, CourseGuidanceItem } from '@/shared/types/graduation';
import { guidanceItemReason, guidanceGapSummary } from '@/domain/graduation/guidance-presentation';
const categoryLabel: Record<string, string> = { majorFoundation: '전공기초', majorRequired: '전공필수', majorElective: '전공선택', generalRequired: '교양필수', generalElective: '교양선택' };
function CourseList({ courses, status = 'required', onConfirm }: { onConfirm?: (codes: string[]) => void; courses: CourseGuidanceItem[]; status?: 'required' | 'candidate' | 'review' | 'completed' }) {
  return <ul className="guidance-course-list">{courses.map(c => <li className="guidance-course" key={`${c.category}-${c.code}`}><strong className="guidance-course-name">{c.name}</strong><div className="guidance-badges"><span>과목코드 {c.code}</span><span>{c.credits}학점</span><span>{categoryLabel[c.category] ?? c.category}</span><span>{c.recommendedYear ? `권장 ${c.recommendedYear}학년${c.recommendedSemester ? ` ${c.recommendedSemester}학기` : ' · 학기 미확인'}` : '권장 시기 미확인'}</span></div><p className="guidance-reason">{guidanceItemReason(c, status)}</p>{onConfirm && c.requirementDesignation === "confirmed" && c.recognitionKind === "transfer-recognition-unresolved" && <button className="onboarding-secondary" onClick={() => onConfirm([c.code])}>이수한 적 없음 · 수강 필요로 반영</button>}<details className="guidance-evidence"><summary>판정 근거</summary><p>{c.reason}</p>{c.sourceId && <p>자료 식별자: {c.sourceId}</p>}{c.locator && <p>원본 위치: {c.locator}</p>}</details></li>)}</ul>;
}
export default function CourseGuidanceView({ guidance: g, onConfirm }: { guidance: CourseGuidance; onConfirm?: (codes: string[]) => void }) {
  return <section className="card course-guidance" aria-label="과목 이수 안내"><header><h2>{g.mode === 'personal' ? '앞으로 이수할 과목' : '선택 교육과정의 필수·기초 이수체계'}</h2><p>{g.mode === 'curriculum' ? '성적표 분석 전의 교육과정 안내입니다. 개인 미이수 목록이 아닙니다.' : '근거가 확인된 과목과 영역 선택 후보를 안내합니다.'} 이번 학기 개설·분반은 미확인입니다.</p></header><h3>{g.mode === 'personal' ? '확인된 남은 필수과목' : '개별 필수 요건'} · {g.remaining.length}과목</h3>{g.remaining.length ? <CourseList courses={g.remaining} /> : <p>확인된 남은 필수과목 없음. 전체 목록 확인 여부는 자료 안내를 확인하세요.</p>}{g.pools.map(p => <details className="guidance-section" key={p.id}><summary>{categoryLabel[p.label] ?? p.label} · 후보 {p.candidates.length}과목{p.review ? ' · 인정 검토 필요' : ''}</summary><p className="guidance-condition">{p.condition}</p>{p.review && <p>인정 검토 중으로, 표시된 차이는 확정 부족량이 아닙니다.</p>}<CourseList courses={p.candidates} status="candidate" /></details>)}{g.recognitionReview.filter(c => c.recognitionKind === 'transfer-recognition-unresolved' && c.requirementDesignation === 'confirmed').length > 0 && <details className="guidance-section"><summary>이수내역 없는 필수과목 · 편입 인정 확인</summary><p>필수 지정은 확인했습니다. 이전학교에서도 미이수라면 수강이 필요합니다. 직접 확인은 개인 수강계획에만 반영하며 공식 인정·면제 판정을 바꾸지 않습니다.</p>{onConfirm && <button className="onboarding-secondary" onClick={() => onConfirm(g.recognitionReview.filter(c => c.recognitionKind === 'transfer-recognition-unresolved' && c.requirementDesignation === 'confirmed').map(c => c.code))}>아래 과목 모두 이수한 적 없음 · 수강 필요로 반영</button>}<CourseList courses={g.recognitionReview.filter(c => c.recognitionKind === 'transfer-recognition-unresolved' && c.requirementDesignation === 'confirmed')} status="review" onConfirm={onConfirm} /></details>}{g.recognitionReview.filter(c => c.recognitionKind !== 'transfer-recognition-unresolved' || c.requirementDesignation !== 'confirmed').length > 0 && <details className="guidance-section"><summary>대체 승인 대기 · 인정 근거 확인</summary><CourseList courses={g.recognitionReview.filter(c => c.recognitionKind !== 'transfer-recognition-unresolved' || c.requirementDesignation !== 'confirmed')} status="review" /></details>}{g.dataGaps.length > 0 && <details className="guidance-section"><summary>과목 요건 자료 안내 · {g.dataGaps.length}건</summary><p>{guidanceGapSummary(g.dataGaps)}</p><ul className="guidance-gap-list">{g.dataGaps.map((gap, i) => <li key={i}>{gap}</li>)}</ul></details>}{g.completed.length > 0 && <details className="guidance-section"><summary>이수 완료 · {g.completed.length}과목</summary><CourseList courses={g.completed} status="completed" /></details>}</section>;
}
